# Copyright (c) 2013, Neville-Neil Consulting
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
# Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# Neither the name of Neville-Neil Consulting nor the names of its 
# contributors may be used to endorse or promote products derived from 
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Author: George V. Neville-Neil
#
# Description: A set of libraries to process PTP log files.  Used by
# various command line tools in this directory.
#

# Functions for working with PTP log output

#
# Returns a data frame based on a PTPd log file
#
# @file - A properly formatted PTP log file generated by the daemon
#
ptpLogRead <- function(file) {
    log = read.table(file, fill=TRUE, sep=",", col.names=c("timestamp", "state", "clockID", "delay", "offset", "master.to.slave", "slave.to.master", "drift", "packet"), blank.lines.skip=TRUE, header=FALSE, skip=100)
    return (log)
}

#
# Graphs a dataframe returned by a call to ptplog
#
# @logframe - A data frame returned by ptpLogRead
# @value - Graph only a specific value rather than the four major ones.
# @output - An optional file name to place a PNG of the graph into
#
ptpGraph <- function(logframe, value, output) {
    if (!missing(output))
        png(filename=output, height=960, width=1280, bg="white")
    if (missing(value)) {
        ymin = min(min(logframe$offset, na.rm=TRUE), min(logframe$delay, na.rm=TRUE),
            min(logframe$master.to.slave, na.rm=TRUE),
            min(logframe$slave.to.master, na.rm=TRUE))
        ymax = max(max(logframe$offset, na.rm=TRUE), max(logframe$delay, na.rm=TRUE),
            max(logframe$master.to.slave, na.rm=TRUE),
            max(logframe$slave.to.master, na.rm=TRUE))
        plot(logframe$delay, y=NULL, xaxt = "n" ,type="n", ylim=range(ymin, ymax),
             main="PTP Results", xlab="Time", ylab="Nanoseconds")
        legend(100, ymax,
               c("Delay", "Offset", "M->S", "S->M"), col=c("orange", "blue", "red", "green"), pch=21:24)
        points(logframe$offset, y=NULL, cex=.1, col="blue", pch=21)
        points(logframe$master.to.slave, y=NULL, cex=.1, col="red", pch=22)
        points(logframe$slave.to.master, y=NULL, cex=.1, col="green", pch=23)
        points(logframe$delay, y=NULL, cex=.1, col="orange", pch=24)
    } else {
        ymin = min(logframe[[value]], na.rm=TRUE)
        ymax = max(logframe[[value]], na.rm=TRUE)
        plot(logframe[[value]], y=NULL, xaxt = "n" ,type="n",
             ylim=range(ymin, ymax),
             main="PTP Results", xlab="Time", ylab="Nanoseconds")
        points(logframe[[value]], y=NULL, cex=.1, col="red", pch=21)
    }
}
    
#
# Compare two log files on a graph
#
# @loga - data frame read using ptplogRead
# @logb - data frame read using ptplogRead
# @value - column of the log file to compare
#          e.g. offset, delay, slave.to.master, master.to.slave
# @output - an output file name for a PNG image
ptpCompare <-function(loga, logb, value, output) {
    if (!missing(output))
        png(filename=output, height=960, width=1280, bg="white")
    # If the caller does not specify which value to compare, compare them all
    if (missing (value)) {
        ymin = min(min(loga$offset, na.rm=TRUE), min(loga$delay, na.rm=TRUE),
            min(loga$master.to.slave, na.rm=TRUE),
            min(loga$slave.to.master, na.rm=TRUE))
        ymax = max(max(loga$offset, na.rm=TRUE), max(loga$delay, na.rm=TRUE),
            max(loga$master.to.slave, na.rm=TRUE),
            max(loga$slave.to.master, na.rm=TRUE))

        plot(loga$delay, y=NULL, xaxt = "n" ,type="n", ylim=range(ymin, ymax),
             main="PTP Results", xlab="Time", ylab="Nanoseconds")
        points(loga$delay, y=NULL, cex=.1, col="black", pch=24)
        points(loga$offset, y=NULL, cex=.1, col="blue", pch=21)
        points(loga$master.to.slave, y=NULL, cex=.1, col="purple", pch=22)
        points(loga$slave.to.master, y=NULL, cex=.1, col="green", pch=23)

        points(logb$delay, y=NULL, cex=.1, col="black", pch=24)
        points(logb$offset, y=NULL, cex=.1, col="deeppink", pch=21)
        points(logb$master.to.slave, y=NULL, cex=.1, col="blue", pch=22)
        points(logb$slave.to.master, y=NULL, cex=.1, col="red", pch=23)
        legend(100, ymax,
               c("Delay1", "Offset1", "M->S_1", "S->M_1", "Delay2", "Offset2", "M->S_2", "S->M_w"), col=c("black", "blue", "purple", "green", "black", "deeppink", "blue", "red"), pch=21:24)
    } else {
        ymin = min(min(loga[[value]], na.rm=TRUE), min(logb[[value]], na.rm=TRUE))
        ymax = max(max(loga[[value]], na.rm=TRUE), max(logb[[value]], na.rm=TRUE))
        plot(loga[[value]], y=NULL, xaxt = "n" ,type="n", ylim=range(ymin, ymax),
             main="PTP Results", xlab="Time", ylab="Nanoseconds")
        points(loga[[value]], y=NULL, cex=.1, col="red", pch=21)

        points(logb[[value]], y=NULL, cex=.1, col="blue", pch=22)
        legend(100, ymax,
               c(paste(value,"1"), paste(value, "2")), col=c("red", "blue"), pch=21:22)
#        axis(1, at=loga$timestamp, labels=logb$timestamp, )
    }
}

# Functions for working with PTPd quality files

#
# Returns a data frame based on a PTPd quality file.
ptpQualityRead <- function(file) {
    log = read.table(file, file=TRUE, sep=",", col.names=c("packet", "time"), blank.lines.skip=TRUE, header=FALSE)
    return (log)
}

ptpQualityCompare <- function(loga, logb, output) {
}


# Functions for deriving various statistics over a PTP log

ptpStats <- function(ptplog) {
    cat("Offset",
        "\nmin:", min(ptplog$offset, na.rm=TRUE),
        " max: ", max(ptplog$offset, na.rm=TRUE),
        " median: ", median(ptplog$offset, na.rm=TRUE),
        " mean: ", mean(ptplog$offset, na.rm=TRUE),
        "\nstd dev: ", sd(ptplog$offset, na.rm=TRUE),
        " variance: ", var(ptplog$offset, na.rm=TRUE), "\n")
    cat("Delay",
        "\nmin:", min(ptplog$delay, na.rm=TRUE),
        " max: ", max(ptplog$delay, na.rm=TRUE),
        " median: ", median(ptplog$delay, na.rm=TRUE),
        " mean: ", mean(ptplog$delay, na.rm=TRUE),
        "\nstd dev: ", sd(ptplog$delay, na.rm=TRUE),
        " variance: ", var(ptplog$delay, na.rm=TRUE), "\n")
    cat("Master -> Slave",
        "\nmin:", min(ptplog$master.to.slave, na.rm=TRUE),
        " max: ", max(ptplog$master.to.slave, na.rm=TRUE),
        " median: ", median(ptplog$master.to.slave, na.rm=TRUE),
        " mean: ", mean(ptplog$master.to.slave, na.rm=TRUE),
        "\nstd dev: ", sd(ptplog$master.to.slave, na.rm=TRUE),
        " variance: ", var(ptplog$master.to.slave, na.rm=TRUE), "\n")
    cat("Slave -> Master",
        "\nmin:", min(ptplog$slave.to.master, na.rm=TRUE),
        " max: ", max(ptplog$slave.to.master, na.rm=TRUE),
        " median: ", median(ptplog$slave.to.master, na.rm=TRUE),
        " mean: ", mean(ptplog$slave.to.master, na.rm=TRUE),
        "\nstd dev: ", sd(ptplog$slave.to.master, na.rm=TRUE),
        " variance: ", var(ptplog$slave.to.master, na.rm=TRUE), "\n")
}
