.\" -*- nroff -*"
.TH ptpd 8 "January, 2010" "version 2rc1" "Precision Time Protocol daemon"
.SH NAME
ptpv2d \- Precision Time Protocol daemon (1588-2008)
.SH SYNOPSIS
.B ptpv2d
[?]
[-c]
[-f FILE]
[-d]
[-D]
[-x]
[-t]
[-a NUMBER,NUMBER]
[-w NUMBER]
[-b NAME]
[-u ADDRESS]
[-e]
[-h]
[-l NUMBER,NUMBER]
[-o NUMBER]
[-i NUMBER]
[-n NUMBER]
[-y NUMBER]
[-m NUMBER]
[-g]
[-v NUMBER]
[-r NUMBER]
[-s NUMBER]
[-p NUMBER]
[-q NUMBER]

.SH DESCRIPTION
Implements the Precision Time Protocol (PTP) Version 2 as defined by the IEEE
1588-2008 standard. PTP was developed to provide very precise time
coordination of LAN connected computers.
.PP
PTPd is a complete implementation of the IEEE 1588 v2 specification for a
standard (ordinary) clock. PTPd has been tested with and is known
to work properly with other IEEE 1588 implementations. The source code
for PTPd is freely available under a BSD-style license. Thanks to
contributions from users, PTPd is becoming an increasingly portable,
interoperable, and stable IEEE 1588 implementation.
.PP
For more information, see http://ptpd.sourceforge.net/
.SH OPTIONS
.TP
.B \-?
display a short help text
.TP
.B \-c
run in command line (non-daemon) mode
.TP
.B \-f FILE
send output to FILE
.TP
.B \-d
display stats
.TP
.B \-D
display stats in .csv format
.TP
.B \-x
do not reset the clock if off by more than one second
.TP
.B \-t
do not adjust the system clock
.TP
.B \-a NUMBER,NUMBER
specify clock servo P and I attenuations
.TP
.B \-w NUMBER
specify one way delay filter stiffness
.TP
.B \-b NAME
bind PTP to network interface NAME
.TP
.B \-u ADDRESS
also send uni-cast to ADDRESS
.TP
.B \-e
run in ethernet mode (level2)
.TP
.B \-h
run in End to End mode
.TP
.B \-l NUMBER,NUMBER
specify inbound, outbound latency in nsec
.TP
.B \-o NUMBER
specify current UTC offset
.TP
.B \-i NUMBER
specify PTP domain number
.TP
.B \-n NUMBER
specify announce interval in 2^NUMBER sec
.TP
.B \-y NUMBER
specify sync interval in 2^NUMBER sec
.TP
.B \-m NUMBER
specify max number of foreign master records
.TP
.B \-g
run as slave only
.TP
.B \-v NUMBER
specify system clock allen variance
.TP
.B \-r NUMBER
specify system clock accuracy
.TP
.B \-s NUMBER
specify system clock class
.TP
.B \-p NUMBER
specify priority1 attribute
.TP
.B \-q NUMBER
specify priority2 attribute

.SH AUTHOR
Gael Mace <gael_mace@users.sourceforge.net> & Alexandre Van Kempen. This manual page
was written by Gael Mace for any Linux environment project.
